// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcaPeLRsUtewrAo_vabrM3XTyGV72P2yU',
    appId: '1:23212618985:web:3599a1e8077cf6fdcbac78',
    messagingSenderId: '23212618985',
    projectId: 'chat-app-7c20f',
    authDomain: 'chat-app-7c20f.firebaseapp.com',
    storageBucket: 'chat-app-7c20f.appspot.com',
    measurementId: 'G-7S12QKL562',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCyebpeHJnvEYCQyMV2-EHS4Vxxrjp5NE',
    appId: '1:23212618985:android:09fbe03539c9dfb5cbac78',
    messagingSenderId: '23212618985',
    projectId: 'chat-app-7c20f',
    storageBucket: 'chat-app-7c20f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG__rHLL0OW3w44go7sJTAwtQKtPWKZfQ',
    appId: '1:23212618985:ios:daebaae835c56945cbac78',
    messagingSenderId: '23212618985',
    projectId: 'chat-app-7c20f',
    storageBucket: 'chat-app-7c20f.appspot.com',
    iosClientId: '23212618985-3gut26mbkpl90abfk75t2fde0vk8r6nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
